name: Stock Price Notification_US

on:
  schedule:
    # 每天台灣時間 08:00 運行 (UTC+8)
    # 注意: GitHub Actions 使用 UTC 時間,所以需要調整
    - cron: "00 14 * * 1-5" # UTC 00:30 (台灣時間 22:00), 週一到週五
    - cron: "00 15 * * 1-5" # UTC 00:30 (台灣時間 23:00), 週一到週五
    - cron: "00 13 * * 1-5" # UTC 00:30 (台灣時間 21:00), 週一到週五
    - cron: "00 22 * * 0-5" # UTC 00:30 (台灣時間 06:00), 週一到週日
  workflow_dispatch: # 保留手動觸發選項

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock price notification script
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python stock_price_notification_US.py
